version: '3.8'
services:
  db:
    container_name: employ_postgres
    image: postgres
    environment:
      #      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
    #      POSTGRES_DB: main
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    container_name: employ_adminer
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - '3200:8080'

  #docker exec -it employ_php bash
  php:
    container_name: employ_php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./php/config:/usr/local/etc/php
    depends_on:
      - db

  nginx:
    container_name: employ_nginx
    image: nginx:stable-alpine
    ports:
      - '8082:80'
    volumes:
      - .:/app:cached
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - employ_php
      - employ_postgres
      - employ_adminer

volumes: # add persistent data even if container is removed.
  postgres:
  nginx:
  php: